### ISSUE TITLE
깃허브 레포지토리 세팅

### ISSUE THREAD

**Issue by sihyun10** [sihyun10/FE_PS_Final_Refactor#1]
## Description

깃허브 레포지토리 및 PM 관련 규칙 정하기

## Todo List

- [x] 커밋 컨벤션 정하기
- [x] 브랜치 분리 및 관리 규칙 정하기 (PM)
- [x] 이슈 템플릿 만들기
- [x] 이슈 라벨, 이슈 마일스톤 설정하기
- [x] PR 템플릿 만들기
