### ISSUE TITLE
데이터 처리 과정에 대해 분석 및 리펙토링

### ISSUE THREAD

**Issue by 05Castle** [sihyun10/FE_PS_Final_Refactor#11]
## Description

데이터 처리 과정에서,
각 컴포넌트마다 useParams를 통해 data ID를 체크하는 과정이 중복되는 점을 리펙토링.

아래와 같이 두가지 방식을 따로 시도하여 어떤 방법이 나은지 비교/분석 해보자.

※ 각 항목을 시도할 때, 리펙토링 이슈를 세우고 작업할 것!

## Todo List

- [x] 첫번째 방법 : data id 체크 과정을 util 함수화 하여 코드 줄이기
- [ ] 두번째 방법 : data id를 체크하여 현재의 data만 전역 상태로 관리하기 
- [ ] 두 방법에 대해 비교/분석하여 한 가지 방법으로 취합

**Comment by 05Castle** [comment]
두번째 방법을 시도하지 못하였다.
첫번째 방법으로도 리팩토링 전후 결과가 확실히 개선되었음은 확인하였다.

두번째 방법에 대해서는 리팩토링 wiki에 기록할 것.
