### ISSUE TITLE
위키 정리하기

### ISSUE THREAD

**Issue by 05Castle** [sihyun10/FE_PS_Final_Refactor#19]
## Description

지금까지 코드리뷰와 리팩토링 한 내용을 깃허브 위키로 정리하기.
어떻게 진행했는지, 왜 그렇게 했는지, 어떤 고민이 있었고 남았는지 기록하기.

또한 이전 코드와 프로젝트에 대한 전반적인 소개도 위키로 정리할 것.
이는 리팩토링 전과 후를 비교할 수 있도록 하기 위함이며,
나중에 다시 이 문서를 볼 때 기억이 잘 안나도 전체적인 이해에 도움이 될 수 있을 것이다.

## Todo List

- [x] 프로젝트 개요 정리
- [x] 주요 기능 설명 정리
- [x] 컨벤션 업데이트
- [x] 디렉토리 코드리뷰
- [x] 데이터 프로세스 코드리뷰
- [x] 디렉토리 정리 및 재분류 리팩토링
- [x] CommonButton 리팩토링
- [x] 중복 로직 리팩토링(id 체크하고 데이터 가져오는 로직)
- [x] api 관련 리팩토링
- [x] 업로드 모듈 리팩토링
- [x] 회고록
- [x] 회고 내용 체계화해서 정리하기
- [ ] 미팅로그 정리
- [ ] 새롭게 알게 된 내용 정리
